language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
#  - "3.3"
#  - "pypy"

env:
  - DJANGO_VERSION=1.6
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.4.9

# command to install dependencies
install:
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py install

# command to run tests
script:
  - python setup.py test
  - python manage.py test codespeed
